trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'azurite-testcontainers/AzuriteTestContainers.sln'

steps:
- checkout: self

- task: UseDotNet@2
  inputs:
    packageType: 'runtime'
    version: '7.x'

- task: DotNetCoreCLI@2
  displayName: restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: build
    projects: $(solution)
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: test
  inputs:
    command: test
    projects: $(solution)
    arguments: --configuration Release --logger trx --collect:"XPlat Code Coverage"

- task: DotNetCoreCLI@2
  displayName: publish
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)/Output'