version: '3.4'

services:
  kubernetessampleweb:
    image: ${DOCKER_REGISTRY-}kubernetessampleweb
    build:
      context: .
      dockerfile: KubernetesSample.Web/Dockerfile

  kubernetessampleapi:
    image: ${DOCKER_REGISTRY-}kubernetessampleapi
    build:
      context: .
      dockerfile: KubernetesSample.Api/Dockerfile
