apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: kubernetes-sample-api
    image: sample-api:1.0
    ports:
    - containerPort: 8080